### ISSUE TITLE
format date

### ISSUE THREAD

**Issue by PhilippDemmelmair** [PhilippDemmelmair/CAPSTONE-project#15]
As an User, 
I want to have a date, 
that I can read more easily. 

### AC

- [ ] date is in a more readable format

### tasks

- [ ] make a new branch
- [ ] import moment.js
- [ ] format date in teaser component
- [ ] format date on detail site

### complexity

S
