### ISSUE TITLE
User Authentification

### ISSUE THREAD

**Issue by PhilippDemmelmair** [PhilippDemmelmair/CAPSTONE-project#17]
As an Admin, 
I want to restrict the access to my backend, 
so that only permitted Users can use the backend. 

### AC 

- [ ] implemented oAuth for authentification
- [ ] restricted access to backend for logged in admins only

### tasks

- [ ] open new branch
- [ ] implement oAuth for Authentification
- [ ] set up oAuth
- [ ] restrict access to backendroute

### complexity

L
