### ISSUE TITLE
writing posts in the backend

### ISSUE THREAD

**Issue by PhilippDemmelmair** [PhilippDemmelmair/CAPSTONE-project#18]

**Comment by PhilippDemmelmair** [comment]
As an Admin, 
I want to write posts in my backend, 
so that I don't have to manually upload files to the db. 

### AC 

- [ ] there is a form in the backend, where I can write posts
- [ ] posts get stored in the db

### Tasks 

- [ ] create a new branch 
- [ ] create form in backend
- [ ] create method to save post in db

### Complexity M

**Comment by stefankorder** [comment]
Is the form really in the backend?

**Comment by PhilippDemmelmair** [comment]
Yes, I mean Admin-Backend (reachable under url/admin) not Server Backend. I'm always saying, the naming of these two parts of an application is confusing.

**Comment by stefankorder** [comment]
I would call it adminpage or something like this.

**Comment by PhilippDemmelmair** [comment]
Did that.

**Comment by stefankorder** [comment]
perfect 👍🏻
