### ISSUE TITLE
commentstatus can be switched

### ISSUE THREAD

**Issue by PhilippDemmelmair** [PhilippDemmelmair/CAPSTONE-project#20]
As an Admin, 
I want a function to switch the status of a comment, 
so when I reconsider allowing a comment, I can easily change the status. 

### AC

- [ ] Button to change the status of a comment

### task

- [ ] create a new branch 
- [ ] add a button 
- [ ] add a function that toggles the status of a comment
- [ ] new status gets saved in the db

### complexity

S
