### ISSUE TITLE
comments can get deleted

### ISSUE THREAD

**Issue by PhilippDemmelmair** [PhilippDemmelmair/CAPSTONE-project#21]
As an Admin, 
I want to have a delete function for comments, 
so that I can delete comments I don't want to have stored in my db. 

### AC

- [ ] button that deletes a specific comment

### tasks

- [ ] create a new branch
- [ ] add a button
- [ ] add a function that deletes this comment

### complexity

S
