### ISSUE TITLE
DB Connection

### ISSUE THREAD

**Issue by Pe-De-E** [PhilippDemmelmair/CAPSTONE-project#5]
As an Admin,
I want to have a connection to a DB, 
so that I can store Data and collect it from there. 

### AC

- [x] App has a connection to a DB

### Tasks

- [x] create a new branch
- [x] create a db on mongoDB
-  - [x] for db model see graphic below
-  - [x] create collection for blogposts
-  - [x] implement datastructure for blogposts
- [x] store db connection data in .env file in the project
- [x] write function (eg a test) to check if DB is connected

Please be aware that comments are mentioned in the model and the picture to see how they fit in the whole picture later. They will be added in a future sprint in a US future Philipp has to write. 

![Untitled-2022-06-22-1454(1)](https://user-images.githubusercontent.com/56469697/175038805-196d3273-42d6-4808-93e3-bc4d60e3298c.svg)

### Complexity

M

**Comment by desplodur** [comment]
Looks good to me.

**Comment by JessicaLoers** [comment]
Hello Philip 🙂

- I have the following questions and comments: When will you create your data structure, model, schema,  collections and what will they look like?  Is there another user story you can link to?

- Please reconsider this task: _"store data in .env file in the project"_

**Comment by PhilippDemmelmair** [comment]
> Hello Philip 🙂
> 
>     * I have the following questions and comments: When will you create your data structure, model, schema,  collections and what will they look like?  Is there another user story you can link to?
> 
>     * Please reconsider this task: _"store data in .env file in the project"_

Hello, 

i have considered your suggestions. Please have another look.
