### ISSUE TITLE
Load posts from DB

### ISSUE THREAD

**Issue by PhilippDemmelmair** [PhilippDemmelmair/CAPSTONE-project#6]
As an Admin,
I want to load blogposts from the database, 
so that I have a central storage of my data. 

### AC

- [ ] loads blogposts from the database
- [ ] displays the data in the cards on the main page

### Tasks

- [ ] create a new branch
- [ ] include function that fetches all existing blogposts
- [ ] load data in blogpost cards
- [ ] switch from dummy data to actual data from the db 
- [ ] display cards on maipage
- [ ] write test that card is rendered with data

### Complexity

L
