### ISSUE TITLE
own sites for blogposts

### ISSUE THREAD

**Issue by PhilippDemmelmair** [PhilippDemmelmair/CAPSTONE-project#7]
As ab User, 
I want to have a full site with just one blogpost, 
so that I can read the whole article. 

### AC 

- [ ] when the User clicks on a read more button, the user should be sent to a new site with the whole article

### Tasks

- [ ] create a new branch
- [ ]  create a function that routes users to a new site
- [ ]  fetch specific blogpost
- [ ] create blogpost component (like blogpost card on mainpage but without red more button)
- [ ] load data in blogpost component 
- [ ] write test, that blogpost component gets rendered

### Complexity

M

**Comment by JessicaLoers** [comment]
**Hey Philipp** ✌️

**Value proposition:** 
- little typo: As a* User

**AC:**   Is that really the only criteria? You could add something like:
- Teasers of all blogposts are listed 

 **Task:** Maybe I don't understand it properly, but ... 
 -  what do you mean with "fetch" specific blogpost. Usually you fetch all data but the component renders the single  blogpost/article. 
 - same with  "load data in blogpost component"

**If you have any questions, feel free to ask**

**Comment by PhilippDemmelmair** [comment]
Hey, 

fixed the typo. 

AC: this will be done in another US I yet have to write out, since I think of the teasers on the main page and the loading of a whole article as two separate functions. 

Task:

>  ** What do you mean with "fetch" specific blogpost. Usually you fetch all data but the component renders the single 
> blogpost/article. **

I want to load one blogpost in its own site. All my blogposts are grouped in a collection. I don't want to load the whole collection, since I think this would be to much traffic, or to much traffic that could be avoided. I also hope this explains, what I mean with "load data in blogpost component"

Please have another look

**Comment by JessicaLoers** [comment]
Alright then, go ahead 🚀
